-- Immutable compatibility fixture for core plus search 0.1.4 on PostgreSQL.
-- Do not edit this file when entities change. Add a new production migration instead.

create table git_packs (
    id bigint generated by default as identity not null,
    repository_name varchar(255) not null,
    pack_name varchar(255) not null,
    pack_extension varchar(32) not null,
    data bytea not null,
    file_size bigint not null,
    committed boolean not null,
    created_at timestamp(6) with time zone not null,
    committed_at timestamp(6) with time zone,
    primary key (id),
    constraint uk_pack_repo_name_ext unique (repository_name, pack_name, pack_extension)
);

create index idx_pack_repo on git_packs (repository_name);
create index idx_pack_repo_name on git_packs (repository_name, pack_name);
create index idx_pack_repo_committed on git_packs (repository_name, committed);

create table git_reflog (
    id bigint generated by default as identity not null,
    version bigint,
    repository_name varchar(255) not null,
    ref_name varchar(1024) not null,
    old_id varchar(40),
    new_id varchar(40),
    who_name varchar(255),
    who_email varchar(255),
    who_when timestamp(6) with time zone not null,
    message varchar(2048),
    primary key (id)
);

create index idx_reflog_repo on git_reflog (repository_name);
create index idx_reflog_repo_ref on git_reflog (repository_name, ref_name);

create table git_commit_index (
    id bigint generated by default as identity not null,
    repository_name varchar(255) not null,
    object_id varchar(40) not null,
    short_message varchar(2048),
    full_message varchar(8192),
    author_name varchar(255),
    author_email varchar(255),
    commit_time timestamp(6) with time zone,
    changed_paths varchar(16384),
    changed_text varchar(262144),
    primary key (id),
    constraint uk_commit_repo_object unique (repository_name, object_id)
);

create index idx_commit_repo on git_commit_index (repository_name);
create index idx_commit_repo_time on git_commit_index (repository_name, commit_time);
create index idx_commit_repo_author on git_commit_index (repository_name, author_email);
