# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      jgit:
        patterns:
          - "org.eclipse.jgit:org.eclipse.jgit"
      hibernate:
        patterns:
          - "org.hibernate.orm:hibernate-core"
          - "org.hibernate.search:hibernate-search-mapper-orm"
          - "org.hibernate.search:hibernate-search-backend-lucene"
      build-plugins:
        patterns:
          - "org.apache.maven.plugins:maven-compiler-plugin"
          - "org.apache.maven.plugins:maven-enforcer-plugin"
          - "org.apache.maven.plugins:maven-surefire-plugin"
          - "org.apache.maven.plugins:maven-jar-plugin"
          - "org.apache.maven.plugins:maven-source-plugin"
          - "org.apache.maven.plugins:maven-javadoc-plugin"
          - "org.apache.maven.plugins:maven-shade-plugin"
          - "org.codehaus.mojo:versions-maven-plugin"
          - "org.jacoco:jacoco-maven-plugin"
