/*
 * Copyright (C) 2026, Carsten Hammer and contributors.
 *
 * This program and the accompanying materials are made available under the
 * terms of the BSD 3-Clause License.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
package io.github.carstenartur.jgit.storage.hibernate;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;

import io.github.carstenartur.jgit.storage.hibernate.schema.LegacyCoreSchemaAdoption;
import io.github.carstenartur.jgit.storage.hibernate.schema.LegacyCoreSchemaAdoptionException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import org.junit.jupiter.api.Test;

class LegacyCoreSchemaAdoptionUnicodeTest {

  private static final String SUPPLEMENTARY_CHARACTER = "\uD83D\uDE80";

  @Test
  void countsUnicodeCodePointsRatherThanUtf16CodeUnits() throws Exception {
    try (Connection connection =
        DriverManager.getConnection("jdbc:h2:mem:legacy_unicode;DB_CLOSE_DELAY=-1")) {
      createLegacySchema(connection);
      insertPack(connection, SUPPLEMENTARY_CHARACTER.repeat(32));

      assertDoesNotThrow(() -> LegacyCoreSchemaAdoption.requireSafeToAdopt(connection));

      updateExtension(connection, SUPPLEMENTARY_CHARACTER.repeat(33));
      assertThrows(
          LegacyCoreSchemaAdoptionException.class,
          () -> LegacyCoreSchemaAdoption.requireSafeToAdopt(connection));
    }
  }

  private static void createLegacySchema(Connection connection) throws Exception {
    try (Statement statement = connection.createStatement()) {
      statement.execute(
          """
          create table git_packs (
            id bigint generated by default as identity primary key,
            repository_name varchar(255) not null,
            pack_name varchar(255) not null,
            pack_extension varchar(255) not null,
            data blob not null,
            file_size bigint not null,
            created_at timestamp not null
          )
          """);
    }
  }

  private static void insertPack(Connection connection, String extension) throws Exception {
    try (PreparedStatement statement =
        connection.prepareStatement(
            """
            insert into git_packs
              (repository_name, pack_name, pack_extension, data, file_size, created_at)
            values (?, ?, ?, ?, ?, ?)
            """)) {
      byte[] data = {1};
      statement.setString(1, "demo");
      statement.setString(2, "pack-a");
      statement.setString(3, extension);
      statement.setBytes(4, data);
      statement.setLong(5, data.length);
      statement.setTimestamp(6, Timestamp.from(Instant.parse("2026-07-28T00:00:00Z")));
      statement.executeUpdate();
    }
  }

  private static void updateExtension(Connection connection, String extension) throws Exception {
    try (PreparedStatement statement =
        connection.prepareStatement("update git_packs set pack_extension = ?")) {
      statement.setString(1, extension);
      statement.executeUpdate();
    }
  }
}
