-- Immutable compatibility fixture for jgit-storage-hibernate-core 0.1.4 on PostgreSQL.
-- Do not edit this file when entities change. Add a new production migration instead.
-- Reftable files are stored in git_packs with pack_extension = 'REFTABLE'.

create table git_packs (
    id bigint generated by default as identity not null,
    repository_name varchar(255) not null,
    pack_name varchar(255) not null,
    pack_extension varchar(32) not null,
    data bytea not null,
    file_size bigint not null,
    committed boolean not null,
    created_at timestamp(6) with time zone not null,
    committed_at timestamp(6) with time zone,
    primary key (id),
    constraint uk_pack_repo_name_ext unique (repository_name, pack_name, pack_extension)
);

create index idx_pack_repo on git_packs (repository_name);
create index idx_pack_repo_name on git_packs (repository_name, pack_name);
create index idx_pack_repo_committed on git_packs (repository_name, committed);

create table git_reflog (
    id bigint generated by default as identity not null,
    version bigint,
    repository_name varchar(255) not null,
    ref_name varchar(1024) not null,
    old_id varchar(40),
    new_id varchar(40),
    who_name varchar(255),
    who_email varchar(255),
    who_when timestamp(6) with time zone not null,
    message varchar(2048),
    primary key (id)
);

create index idx_reflog_repo on git_reflog (repository_name);
create index idx_reflog_repo_ref on git_reflog (repository_name, ref_name);
