-- Generic search projection schema produced by jgit-storage-hibernate-search 0.1.4.

create table git_commit_index (
    id bigint generated by default as identity not null,
    repository_name varchar(255) not null,
    object_id varchar(40) not null,
    short_message varchar(2048),
    full_message varchar(8192),
    author_name varchar(255),
    author_email varchar(255),
    commit_time timestamp(6) with time zone,
    changed_paths varchar(16384),
    changed_text varchar(262144),
    primary key (id),
    constraint uk_commit_repo_object unique (repository_name, object_id)
);

create index idx_commit_repo on git_commit_index (repository_name);
create index idx_commit_repo_time on git_commit_index (repository_name, commit_time);
create index idx_commit_repo_author on git_commit_index (repository_name, author_email);
